# Generated by Django 3.0.5 on 2021-05-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210511_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireComplain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('complain', models.CharField(max_length=500)),
                ('date', models.DateField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalComplain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('complain', models.CharField(max_length=500)),
                ('date', models.DateField(max_length=12)),
            ],
        ),
    ]
