# Generated by Django 3.0.5 on 2021-05-13 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20210513_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firecomplain',
            old_name='complain',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='firecomplain',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='medicalcomplain',
            old_name='complain',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='medicalcomplain',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='policecomplain',
            old_name='complain',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='policecomplain',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='firecomplain',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalcomplain',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='policecomplain',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
