# Generated by Django 3.0.5 on 2021-05-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210513_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcomplain',
            name='latitude',
            field=models.FloatField(default=0.0, max_length=10),
        ),
        migrations.AddField(
            model_name='medicalcomplain',
            name='longitudetude',
            field=models.FloatField(default=0.0, max_length=10),
        ),
    ]
