# Generated by Django 3.0.5 on 2021-05-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210514_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalcomplain',
            old_name='longitudetude',
            new_name='longitude',
        ),
        migrations.AddField(
            model_name='firecomplain',
            name='latitude',
            field=models.FloatField(default=0.0, max_length=10),
        ),
        migrations.AddField(
            model_name='firecomplain',
            name='longitude',
            field=models.FloatField(default=0.0, max_length=10),
        ),
        migrations.AddField(
            model_name='policecomplain',
            name='latitude',
            field=models.FloatField(default=0.0, max_length=10),
        ),
        migrations.AddField(
            model_name='policecomplain',
            name='longitude',
            field=models.FloatField(default=0.0, max_length=10),
        ),
    ]
